:set vb
:set noeb vb t_vb=

set nocompatible
filetype on
filetype off


" EnCoding
set enc=UTF-8
set fileencodings=UTF-8
set fencs=utf8,euc-kr,cp949,cp932,euc-jp,shift-jis,big5,latin1,ucs-2le
set visualbell
set backspace=indent,eol,start
set statusline=%h%F%m%r%=[%l:%c(%p%%)]
set expandtab
set tabstop=4
set shiftwidth=4
set cindent
set autoindent
set smartindent
"filetype indent on
set history=15
set ruler
set showcmd
set nobackup
"set foldmethod=marker
set foldmethod=indent
set foldlevel=99
set hlsearch
set background=dark
set number
set visualbell
set noswapfile
set cursorline 
set laststatus=2

" Enable folding with the spacebar
nnoremap <space> za

"Prevent freezing vim without tmux
set noeb vb t_vb=

syntax on

map <F1> <ESC>:Tlist<CR>
"map <F2> <ESC>:NERDTree<CR>
nnoremap <silent> <special> <F2> :NERDTreeToggle <Bar> if &filetype ==# 'nerdtree' <Bar> wincmd p <Bar> endif<CR>

map <F3> <ESC>:w<CR>
map <F4> <ESC>:wq<CR>

map <F6> <ESC>:vs<CR>
map <F7> <ESC>:sp<CR>
map <F8> <ESC>:new<CR>
map <F9> <ESC>:close<CR>
map <C-TAB> <C-p>

"ctags
map <C-}> :exec("tag /".expand("<cword>"))<CR>  
map <C-\> :tab split<CR>:exec("tag ".expand("<cword>"))<CR>  
map <A-]> :vsp <CR>:exec("tag ".expand("<cword>"))<CR>

let mapleader=","
let python_highlight_all = 1

" Vundle
set nocompatible              " be iMproved
filetype on
filetype off                  " required!

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
" required!
Plugin 'gmarik/vundle'
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'
Plugin 'tmhedberg/SimpylFold'
"Plugin 'vim-syntastic/syntastic'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" vim-scripts repos
Plugin 'L9'
Plugin 'FuzzyFinder'
Plugin 'jnurmine/Zenburn'
" non-GitHub repos
Plugin 'The-NERD-tree'

Plugin 'Source-Explorer-srcexpl.vim'
" Plugin 'pyflakes'
Plugin 'Python-Syntax'
Bundle 'Valloric/YouCompleteMe'
" Plugin 'AutoComplPop'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'heavenshell/vim-pydocstring'
Plugin 'junegunn/fzf.vim'
Plugin 'mileszs/ack.vim'
Plugin 'w0rp/ale'
call vundle#end()             " required
filetype plugin indent on     " required!
"
" Brief help
" :PluginList          - list configured bundles
" :PluginInstall(!)    - install (update) bundles
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle commands are not allowed.


" syntastic
"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

"let g:syntastic_always_populate_loc_list = 0
"let g:syntastic_auto_loc_list = 1
"let g:syntastic_check_on_open = 1
"let g:syntastic_check_on_wq = 1
"let g:syntastic_python_checkers = ['flake8']

"colorscheme molokai
colors zenburn
highlight Comment cterm=bold
set colorcolumn=120

" fzf setting
set rtp+=~/.fzf
" fzf.vim setting
nmap ; :Buffers<CR>
nmap <Leader>t :Files<CR>
nmap <Leader>r :Tags<CR>
nmap <Leader>g :GFiles<CR>

"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>


